# Generated by Django 5.1.1 on 2024-10-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todoid', models.AutoField(primary_key=True, serialize=False)),
                ('tododescription', models.TextField(blank=True, null=True)),
                ('tododone', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=175)),
                ('password', models.CharField(max_length=85)),
                ('email', models.CharField(max_length=195)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
